Repository nextras/orm, pull requests merged in 2022-01, with the labels that each got.

#552 Add missing array key checks when using the `debug_backtrace()` function
  src/Repository/PersistenceHelper.php
Labels: bug

#554 Added `ICollection::fetchChecked()`
  docs/collection.md
  src/Collection/ArrayCollection.php
  src/Collection/DbalCollection.php
  src/Collection/EmptyCollection.php
  src/Collection/HasManyCollection.php
  src/Collection/ICollection.php
  tests/cases/integration/Collection/collection.phpt
Labels: feature

#556 Support nullable classes definition with '?'
  src/Entity/Reflection/MetadataParser.php
  tests/cases/unit/Entity/Reflection/PropertyMetadata.isValid().phpt
Labels: bug

#557 Add usage example of {wrapper} into docs [closes #553]
  docs/entity.md
Labels: doc
